os: windows
language: node_js
node_js:
  - 9

branches:
  only:
  - master
  - develop

script: npm run build:w3x

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ttay24"
  - git config --local user.email "$GITHUB_TAG_EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  file: 
    - "build/Tribute_Reforged.w3x"
  skip_cleanup: true
  draft: true
  on:
    branch: develop

cache:
  directories:
    - node_modules